name: "build"
on: [ "pull_request", "push" ]
jobs:
  build:
    strategy:
      matrix:
        java: [ "16" ]
        os: [ "ubuntu-latest" ]
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - uses: gradle/wrapper-validation-action@v1
      - name: "setup jdk ${{ matrix.java }}"
        uses: "actions/setup-java@v2"
        with:
          distribution: 'adopt'
          java-version: "${{ matrix.java }}"
      - name: "build"
        run: "./gradlew build"
